### ISSUE TITLE
Topic queues don't populate

### ISSUE THREAD

**Issue by dsandstrom** [arempe93/bunny-mock#9]
I can't get a queue to receive messages.  I've tried the latest bunny/bunny-mock.  However, I need to use bunny v1.4x and bunny-mock v1.x in my app.

I've tried to run your example test and it fails:
```
it 'should route messages from exchanges' do
  channel = BunnyMock.new.start.channel

  xchg = channel.topic 'xchg.topic'
  queue = channel.queue 'queue.test'

  xchg.publish 'Routed message', routing_key: '*.test'

  expect(queue.message_count).to eq(1)
  expect(queue.pop[:message]).to eq('Routed message')
end
```

Here is an example app that fails for me: https://github.com/dsandstrom/bunny_mock_test/blob/master/spec/models/bunny_spec.rb.

**Comment by arempe93** [comment]
I'll clone and look at this sometime today

**Comment by arempe93** [comment]
hey @dsandstrom - seems to have been another typo in the readme :smile:

the queue was never bound to the exchange before the message was published in the example.

**Comment by dsandstrom** [comment]
Thanks for looking into this so quickly.
